import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from '@/components/providers';
import Layout from "@/components/layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "chatox",
    description: "Generated by create next app",
    manifest: "/manifest.json",
    fbAppId: "1160514961715739",
};
export const viewport = {
    themeColor: "#FFFFFF"
};

export default function RootLayout({ children }) {
    return (
            <SessionWrapper>
                <html lang="en">
                    <head>
                        <link rel="icon" href="https://raw.githubusercontent.com/JoeAbdelghany/portfolioWebsite/main/public/assets/images/logo/favicon/favicon.ico" />
                    </head>
                    <body className={inter.className}>
                        <Layout>
                            {children}
                        </Layout>
                    </body>
                </html>
            </SessionWrapper>
    );
}
