import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "chatox",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport = {
  themeColor: "#FFFFFF"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link rel="icon" href="https://raw.githubusercontent.com/JoeAbdelghany/portfolioWebsite/main/public/assets/images/logo/favicon/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
